sonar.projectKey=PSA-Analise-Text-To-SQL_text-to-sql
sonar.organization=psa-analise-text-to-sql
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=**/venv/**, **/.venv/**, **/env/**, **/.tox/**, **/dist/**, **/build/**
sonar.cpd.exclusions=**/migrations/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.tests=tests
sonar.test.inclusions=**/test_*.py, **/*_test.py

sonar.python.version=3.12
sonar.language=py

sonar.scm.disabled=false
